version: '3'
services:
  mobile-render:
    build: ./mobile-render-service
    ports:
      - '${MOBILE_RENDER_PORT}:${MOBILE_RENDER_PORT}'
    environment:
      - PORT=${MOBILE_RENDER_PORT}
    restart: always

  recepies-service:
    build: ./recepies-service
    ports:
      - '${RECEPIES_SERVICE_PORT}:${RECEPIES_SERVICE_PORT}'
    environment:
      - PORT=${RECEPIES_SERVICE_PORT}
    restart: always

  gql-gateway-service:
    build: ./gql-gateway-service
    ports:
      - '${GQL_GATEWAY_SERVICE_PORT}:${GQL_GATEWAY_SERVICE_PORT}'
    environment:
      - PORT=${GQL_GATEWAY_SERVICE_PORT}
    restart: always
